### ISSUE TITLE
Should provide claim `sid` for use in oauth2/callback

### ISSUE THREAD

**Issue by jonalu** [navikt/mock-oauth2-server#135] opened 2021-11-22 14:56 UTC
The `sid` claim is required by [wonderwall](https://github.com/nais/wonderwall).

It can be provided manually in the custom claims input, but it could/should provide a unique `sid` upon login.

Example wonderwall error when `sid` not provided:
```
{"level":"error","service":"wonderwall","httpRequest":{"proto":"HTTP/1.1","requestID":"4a73e2af-3101-4880-b792-56d50f9425f1","requestMethod":"GET","requestPath":"/jobbtreff/oauth2/callback"},"error":"callback: validating id_token: validating id_token: required claim \"sid\" was not found","timestamp":"2021-11-22T15:51:46.769561+01:00","message":"error in route: callback: validating id_token: validating id_token: required claim \"sid\" was not found"}
```

**Comment by tronghn** [comment] 2021-11-22 15:47
I disagree. Wonderwall incorrectly assumes that every OP must provide the `sid` claim in the id_token, which would be the case if the OP supported the [OpenID Connect Front-Channel Logout](https://openid.net/specs/openid-connect-frontchannel-1_0.html#OPLogout) specification. This would be indicated by the  `frontchannel_logout_session_supported` property in the metadata discovery document, which mock-oauth2-server does not explicitly provide and thus does not support.

I suggest that the issue is solved within wonderwall instead. I can open a proper issue there when I'm back from vacation 🙂

**Comment by tronghn** [comment] 2021-12-06 11:09
Wonderwall issue here: https://github.com/nais/wonderwall/issues/7

Closing this remaining issue as a duplicate of #7.

**Closed by tronghn** 2021-12-06 11:09 UTC
